<a href="https://colab.research.google.com/github/sayprincekumar20/NLP/blob/main/PreProcessing_for_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df= pd.read_csv("IMDB Dataset.csv")
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['review'][2]

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

**Convert text into Lower case**

In [ ]:
# Convert into lower case
df['review'][2].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [ ]:
# Convert all reviwe column text into lower case
df['review']= df['review'].str.lower()

In [ ]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

**Remove  HTML Tags**

In [ ]:
# Remove all HTML Tags
df['review'][2]

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [ ]:
import re
def remove_html_tags(text):
  pattern= re.compile('<.*?>')
  return pattern.sub(r'',text)

In [ ]:
remove_html_tags(df['review'][2])

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [ ]:
# To apply on all datasets
df['review']= df['review'].apply(remove_html_tags)

In [ ]:
df['review'][2]

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

**Remove URL **

In [ ]:
def remove_url(text):
  pattern= re.compile(r'https?://\S+|WWW\.\S+')
  return pattern.sub(r'', text)

In [ ]:
text1='This is my github repo https://github.com/sayprincekumar20/NLP/tree/main'

In [ ]:
text1

'This is my github repo https://github.com/sayprincekumar20/NLP/tree/main'

In [ ]:
remove_url(text1)

'This is my github repo '

In [ ]:
# to apply on particluate data row
remove_url(df['review'][5])

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [ ]:
# To apply on entire datasets
df['review']= df['review'].apply(remove_url)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

Remove Punctuation: !,?,,,",#,$,&,*,^,%,@,{,},;,{,},(,) etc


In [ ]:
# why remove punctuation
# bcz they behave as a words when you split the text


In [ ]:
import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude= string.punctuation

In [ ]:
# Normal code : They takes more time
def remove_punc(text):
  for char in exclude:
    text= text.replace(char,'')
  return text


In [ ]:
text= 'string. With, Punctuation?'

In [ ]:
print(remove_punc(text))

string With Punctuation


In [ ]:
# so used this code to remove punctuation it is faster than normal code
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [ ]:
print(remove_punc1(text))

string With Punctuation


In [ ]:
df['review']= df['review'].apply(remove_punc1)

In [ ]:
df['review'][5]

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

**Chat word treatment**

GN= Good Night

GM= Good morning

ASAP= as soon as possible

imho, fyi, etc









In [ ]:
chat_words= pd.read_csv("Abbreviations short forms slangs and their meanings.csv")
chat_words.head()

Word                         Meaning
0                                 4YEO             For Your Eyes Only
1       AAMOF                                     As a Matter of Fact
2  ACK                                                 Acknowledgment
3     AFAIK                                          As far as I know
4        AFAIR                          As far as I remember / recall

In [ ]:
chat_words.shape

(338, 2)

In [ ]:
chat_words['Word '][1]

'AAMOF                         '

In [ ]:
chat_words_dict={}
for index, row in chat_words.iterrows():
  word= str(row['Word ']).strip() # remove space
  meaning= row['Meaning']
  chat_words_dict[word]= meaning

In [ ]:
chat_words_dict

{'4YEO': 'For Your Eyes Only',
 'AAMOF': 'As a Matter of Fact',
 'ACK': 'Acknowledgment',
 'AFAIK': 'as far as I know',
 'AFAIR': 'As far as I remember / recall',
 'AFK': 'away from keyboard',
 'AKA': 'Also known as',
 'B2K BTK': 'Back to Keyboard',
 'BTT': 'Back to Topic',
 'BTW': 'By the Way',
 'B/C': 'Because',
 'C&P': 'Copy and Paste',
 'CU': 'See you',
 'CYS': 'Check your Settings',
 'DIY': 'Do it yourself',
 'EOBD': 'End of Business Day',
 'EOD': 'End of Day',
 'EOM': 'End of Message',
 'EOT': 'End of Thread / .. Text / .. Transmission',
 'FAQ': 'Frequently asked Questions',
 'FACK': 'Full Acknowledge',
 'FKA': 'Formerly known as',
 'FWIW': "For what it's Worth",
 'FYI / JFYI': '(Just) For your Information',
 'FTW': 'Fuck the World / For the Win',
 'HF': 'Have fun',
 'HTH': 'Hope this Helps',
 'IDK': "I don't know",
 'IIRC': 'if I recall/remember correctly',
 'IMHO': 'In my Humble Opinion',
 'IMO': 'In my opinion',
 'IMNSHO': 'In my not so Humble / Honest Opinion',
 'IOW': 'In ot

In [ ]:
def chat_conversion(text):
  new_text = []
  for w in text.split():
     if w.upper() in chat_words_dict:
       new_text.append(chat_words_dict[w.upper()])
     else:
       new_text.append(w)
  return " ".join(new_text)



In [ ]:
chat_conversion('IMHO he is the best')

'In my Humble Opinion he is the best'

In [ ]:
# Apply on datasets
df['review']= df['review'].apply(chat_conversion)

In [ ]:
df['review'][4]

'petter matteis love in the time of money is a visually stunning film to watch mr mattei offers us a vivid portrait about human relations this is a movie that seems to be telling us what money power and success do to people in the different situations we encounter this being a variation on the arthur schnitzlers play about the same theme the director transfers the action to the present time new york where all these different characters meet and connect each one is connected in one way or another to the next person but no one seems to know the previous point of contact stylishly the film has a sophisticated luxurious look we are taken to see how these people live and the world they live in their own habitatthe only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits a big city is not exactly the best place in which human relations find sincere fulfillment as one discerns is the case with most of the people we encounterthe acting i

**Spelling Correction**

use library
   * 1.TextBlob
   * 2.spell checker

In [ ]:
from textblob import TextBlob

In [ ]:
#  i love in the time of money is a visually stunning film to watch
incorrect_text= 'I loveee in the tiime of mney is a visually stunmnning films to wsatch '

In [ ]:
textblb= TextBlob(incorrect_text)
textblb.correct().string

'I love in the time of money is a usually stunning films to watch '

**Removing Stop Words**
eg-> a, the, am, are, my, you, him, his, etc

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stopwords.words('english')


['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
def remove_stopwords(text):
  new_text=[]
  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)
  x= new_text[:]
  new_text.clear()
  return " ".join(x)


In [ ]:
remove_stopwords(' i love in the time of money is a visually stunning film to watch')

' love   time  money   visually stunning film  watch'

In [ ]:
df['review'] = df['review'].apply(remove_stopwords)

In [ ]:
df['review'][4]

'petter matteis love   time  money   visually stunning film  watch mr mattei offers us  vivid portrait  human relations    movie  seems   telling us  money power  success   people   different situations  encounter    variation   arthur schnitzlers play    theme  director transfers  action   present time new york    different characters meet  connect  one  connected  one way  another   next person   one seems  know  previous point  contact stylishly  film   sophisticated luxurious look   taken  see   people live   world  live    habitatthe  thing one gets     souls   picture   different stages  loneliness  one inhabits  big city   exactly  best place   human relations find sincere fulfillment  one discerns   case     people  encounterthe acting  good  mr matteis direction steve buscemi rosario dawson carol kane michael imperioli adrian grenier   rest   talented cast make  characters come alivewe wish mr mattei good luck  await anxiously   next work'

# **Handling Emojis** 😃💁

by two ways
 1. remove
 2. replace by its value


In [ ]:
# Remove Emojis
import re
def remove_emoji(string):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF" # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)


In [ ]:
remove_emoji("game is on 🔥🔥")

'string. With, Punctuation?'

In [ ]:
# Replace Emojis by its value
!pip install emoji
import emoji
print(emoji.demojize('game is on 🔥🔥'))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 33.8 MB/s eta 0:00:00
game is on :fire::fire:


In [ ]:
print(print(emoji.demojize('Hi i am prince kumar 😃💁')))

Hi i am prince kumar :grinning_face_with_big_eyes::person_tipping_hand:
None


 # **Tokenization**

   * 1. tokenization words

e.g., I am from bihar

[I, am, from, bihar]

  * 2. sentence tokenization

e.g.,   I am prince, i am from bihar

  [I am prince, i am from bihar]

#  Using the split function

In [ ]:
# word tokenization
sent1= 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
# Sentence Tokenization
sent2= 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be  great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be  great"]

In [ ]:
# Problem with split (delhi with exclamation marks) added so they behave like new words
# so used regular expression
sent3= 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

2. Regular Expression

In [ ]:
import re
sent4= 'I am going to delhi!'
tokens= re.findall("[\w']+", sent4)
tokens

['I', 'am', 'going', 'to', 'delhi']

Used NLTK Lib

In [ ]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize, sent_tokenize

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
sent5= 'I have a Ph.D in A.I!'

word_tokenize(sent5)


['I', 'have', 'a', 'Ph.D', 'in', 'A.I', '!']

**By solving this problem usied SPACY Library**

for tokenization

In [ ]:
import spacy
nlp= spacy.load('en_core_web_sm')

In [ ]:
doc1= nlp(sent5)

In [ ]:
for token in doc1:
  print(token)

I
have
a
Ph
.
D
in
A.I
!


# Stemming
 by using porter library

in grammer, **inflection** is the modification of a word to express different grammatical categories such as tense, case, voice, aspect, person, number, gender and mood

**inflection words**: walk, walking, walked, walks

**Stemming** : it is a process of reducing nflection in words to their forms such as mapping  group of words to the same stem even   if the itself is not a valid word in the language.

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps= PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
sample= "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [ ]:
sample2= 'petter matteis love in the time of money is a visually stunning film to watch mr mattei offers us a vivid portrait about human relations this is a movie that seems to be telling us what money power and success do to people in the different situations we encounter'
stem_words(sample2)

'petter mattei love in the time of money is a visual stun film to watch mr mattei offer us a vivid portrait about human relat thi is a movi that seem to be tell us what money power and success do to peopl in the differ situat we encount'

Lemmatization : it is also used to work sa same as stemming but problem

Feature | Stemming | Lemmatization

---



Output Type | Root form (may be invalid) | Dictionary word (lemma)

Speed | Faster | Slower

Accuracy | Lower | Higher

Uses Context? | ❌ No | ✅ Yes

Real Words? | Not always | Always

Library Support | nltk.PorterStemmer() | nltk.WordNetLemmatizer()

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer= WordNetLemmatizer()

sentence= "petter matteis love in the time of money is a visually stunning film to watch mr mattei offers us a vivid portrait about human relations this is a movie that seems to be telling us what money power and success do to people in the different situations we encounter"
import string # this should be moved up top with your other imports
string.punctuation= "?:!.,;"
sentence_words= nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in string.punctuation:
        sentence_words.remove(word)
sentence_words= [wordnet_lemmatizer.lemmatize(word,pos='v') for word in sentence_words]
print(sentence_words)

['petter', 'matteis', 'love', 'in', 'the', 'time', 'of', 'money', 'be', 'a', 'visually', 'stun', 'film', 'to', 'watch', 'mr', 'mattei', 'offer', 'us', 'a', 'vivid', 'portrait', 'about', 'human', 'relations', 'this', 'be', 'a', 'movie', 'that', 'seem', 'to', 'be', 'tell', 'us', 'what', 'money', 'power', 'and', 'success', 'do', 'to', 'people', 'in', 'the', 'different', 'situations', 'we', 'encounter']


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


**Bag of words(BOW)**

In [ ]:
import pandas as pd
df= pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [ ]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [ ]:
bow= cv.fit_transform(df['text'])

In [ ]:
# vocab  with index
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [ ]:
# predict : out of vocublary words mein ager  prediction wali words nhi hai to usse ignore kr dega|
cv.transform(['campusx watch and write comment of campusx']).toarray()


array([[2, 1, 0, 1, 1]])

**Bags of n-grams(N-Grams, bi-gram, tri-grams)**

In Natural Language Processing (NLP), an n-gram is a contiguous sequence of "n" items (typically words or characters) from a given text or speech.

🔹 Definition
An n-gram is a sequence of n words:

Unigram (n=1): single word
→ ["I", "love", "coding"]

Bigram (n=2): sequence of 2 words
→ [("I", "love"), ("love", "coding")]

Trigram (n=3): sequence of 3 words
→ [("I", "love", "coding"),("you","are","good")]

and so on...



In [ ]:
import pandas as pd
df= pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [ ]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(ngram_range=(2,2))

In [ ]:
bow= cv.fit_transform(df['text'])

In [ ]:
#vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


TF-IDF : Term frequency- Inverse Document Frequency

In Natural Language Processing (NLP), TF-IDF (Term Frequency–Inverse Document Frequency) is a statistical measure used to evaluate how important a word is to a document in a collection or corpus.

In [ ]:
import pandas as pd
df= pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [ ]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [ ]:
print(tfidf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'write']
