<a href="https://colab.research.google.com/github/sayprincekumar20/NLP/blob/main/Text_Classification_IMDB_text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [28]:
temp_df=pd.read_csv('IMDB Dataset.csv')

In [29]:
df= temp_df.iloc[:10000]

In [30]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [31]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [32]:
df['sentiment'].value_counts()

sentiment
negative    5028
positive    4972
Name: count, dtype: int64

In [33]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(19)

In [35]:
df.drop_duplicates(inplace=True)

<ipython-input-35-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [36]:
df.duplicated().sum()

np.int64(0)

 1. Basic Preprocessing
 2. Remove URLS
 3. Remove punctuation
 4. Remove tags
 5. Convert LowerCase
 6. Remove stopwords


In [37]:
# Remove url
import re
def remove_url(text):
    pattern= re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [38]:
df['review']= df['review'].apply(remove_url)

<ipython-input-38-044f6da46364>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']= df['review'].apply(remove_url)


In [40]:
#Remove Punctuation: !,?,,,",#,$,&,*,^,%,@,{,},;,{,},(,) etc
import string
string.punctuation

exclude= string.punctuation
def remove_punc(text):
  return text.translate(str.maketrans('','',exclude))


In [49]:
df['review']=df['review'].apply(remove_punc)

<ipython-input-49-c4484a742ad8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_punc)


In [50]:
# remove tags
import re
def remove_tags(raw_text):
    cleaned_text= re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [51]:
df['review']= df['review'].apply(remove_tags)

<ipython-input-51-7fcb2f6c6245>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']= df['review'].apply(remove_tags)


In [52]:
df['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen has got polari voices pat too truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard which rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [53]:
# conv into lowercase
df['review']= df['review'].apply(lambda x:x.lower())


<ipython-input-53-ff32d9845b95>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']= df['review'].apply(lambda x:x.lower())


In [54]:
df['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen has got polari voices pat too truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard which rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [55]:
# remove stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw_list= stopwords.words('english')
df['review']= df['review'].apply(lambda x: [item  for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
<ipython-input-55-1307cadb6380>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']= df['review'].apply(lambda x: [item  for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [56]:
df['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen got polari voices pat truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [57]:
df.head()

review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [58]:
X= df.iloc[:,0:1]
y= df.iloc[:,-1]

In [59]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production filming technique ...
2     thought wonderful way spend time hot summer we...
3     basically theres family little boy jake thinks...
4     petter matteis love time money visually stunni...
...                                                 ...
9995  know film meager rating imdb film accompanied ...
9996  show landmark american comedy first sitcom sta...
9997  loved film almost much origional versionwhat t...
9998  saw farewell harry plaza theatre new york city...
9999  preston waters bad summer besides birthday com...

[9981 rows x 1 columns]

In [60]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    positive
9997    positive
9998    positive
9999    positive
Name: sentiment, Length: 9981, dtype: object

In [62]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
y= encoder.fit_transform(y)

In [63]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [72]:
X_train.shape

(7984, 1)

In [73]:
# Applying BOW
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()


In [78]:
X_train_bow= cv.fit_transform(X_train['review']).toarray()
X_text_bow= cv.transform(X_test['review']).toarray()


In [79]:
X_train_bow.shape

(7984, 71782)

In [80]:
from sklearn.naive_bayes import GaussianNB
gnb= GaussianNB()
gnb.fit(X_train_bow, y_train)

GaussianNB()

In [85]:
y_pred= gnb.predict(X_text_bow)
from sklearn.metrics import accuracy_score, confusion_matrix
confusion_matrix(y_test, y_pred)


array([[724, 320],
       [404, 549]])

In [86]:
accuracy_score(y_test, y_pred)

0.6374561842764146

In [87]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()
rf.fit(X_train_bow, y_train)

RandomForestClassifier()

In [88]:
y_pred= rf.predict(X_text_bow)
from sklearn.metrics import accuracy_score, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[877, 167],
       [141, 812]])

In [90]:
accuracy_score(y_test,y_pred)

0.8247371056584877

In [89]:
# limit the features
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8247371056584877

In [91]:
# using N-grams

cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8307461191787682

## **Using TF-IDF**

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf= TfidfVectorizer()
X_train_tf= tf.fit_transform(X_train['review']).toarray()
X_test_tf= tf.transform(X_test['review']).toarray()

In [93]:
rf= RandomForestClassifier()
rf.fit(X_train_tf, y_train)

RandomForestClassifier()

In [94]:
y_pred= rf.predict(X_test_tf)

In [95]:
accuracy_score(y_test, y_pred)


0.8327491236855283